baseURL = 'https://commerce-devkit.org/'
languageCode = 'en-us'
title = 'Commerce DevKit'
theme = 'ananke'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[params]
description = 'The project aims to provide fast, open-source tooling for SAP Commerce development across modern editors.'
project_url = 'https://github.com/commerce-devkit'
background_color_class = 'bg-dark-gray'
body_classes = 'avenir bg-near-white'
cover_dimming_class = 'bg-black-40'
custom_css = ['custom.css']
favicon = 'favicon.svg'

[params.ananke.home]
content_alignment = 'center'
show_recent_posts = false
