baseURL = 'https://commerce-devkit.org/'
languageCode = 'en-us'
title = 'Commerce DevKit'
theme = 'ananke'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']
copyright = 'Commerce DevKit'

[params]
description = 'The project aims to provide fast, open-source tooling for SAP Commerce development across modern editors.'
project_url = 'https://github.com/commerce-devkit'
body_classes = 'commerce-devkit-site'
custom_css = ['custom.css']
favicon = 'favicon.svg'

[params.community]
github = 'https://github.com/commerce-devkit'
discord = 'https://discord.gg/jF9r3Qq9KY'
irc = 'ircs://irc.libera.chat:6697/commerce-devkit'
twitter = 'https://twitter.com/CommerceDevKit'
youtube = 'https://www.youtube.com/@CommerceDevKit'

[social]
twitter = 'CommerceDevKit'

[[menu.main]]
identifier = 'home'
name = 'Home'
url = '/'
weight = 1
